const icons = {
    "planejamento-engenharia": require("./planejamento-engenharia.png"),
    "criar-network-number": require("./criar-network-number.png"),
    "circuitos-pendentes": require("./circuitos-pendentes.png"),
    "projeto-executivo": require("./projeto-executivo.png"),
    "plano-executivo": require("./projeto-executivo.png"),
    "plano-operativo": require("./plano-operativo.png"),
    "base-gerencial": require("./base-gerencial.png"),
    "licenciamento": require("./licenciamento.png"),
    "administrador": require("./administrador.png"),
    "rota-unifilar": require("./rota-unifilar.png"),
    "base-mascaras": require("./base-mascaras.png"),
    "base-cadeias": require("./base-mascaras.png"),
    "base-fisica": require("./base-mascaras.png"),
    "planejamento": require("./planejamento.png"),
    "projeto-e2e": require("./projeto-e2e.png"),
    "geracao-plo": require("./geracao-plo.png"),
    "transporte": require("./transporte.png"),
    "relatorios": require("./relatorios.png"),
    "arrow-back": require("./arrow-back.png"),
    "circuitos": require("./circuitos.png"),
    "topologia": require("./topologia.png"),
    "acesso": require("./acesso.png"),
    "anatel": require("./anatel.png"),
    "mapa": require("./mapa.png"),
    "psbi": require("./psbi.png"),
    "anel": require("./anel.png"),
    "ambv": require("./ambv.png"),
    "hub": require("./hub.png"),
    "mw": require("./mw.png"),

    "relatorios-excel": require("./relatorios-excel.png"),
    "carga": require("./upload.png"),
    "listar": require("./listar.png"),

    "cadastrar-circuitos": require("./cadastrar.png"),
    "carga-taxa-ocupação": require("./taxa.png"),
}

export default icons;
