const data = [
  {
    id: 7,
    name: 'MW',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: 'industry',
    path: '/transporte/mw',
    component: 'MW',
    admin: false,
    children: null
  },
  {
    id: 53,
    name: 'Plano Operativo',
    description: null,
    nivel: 'MENU',
    parent_id: 4,
    icon: 'calendar-check-o',
    path: '/acesso/plano-operativo',
    component: 'PlanoOperativo',
    admin: false,
    children: null
  },
  {
    id: 60,
    name: 'PSBI',
    description: null,
    nivel: 'MENU',
    parent_id: 5,
    icon: null,
    path: '/psbi/psbi',
    component: 'PSBI',
    admin: false,
    children: null
  },
  {
    id: 9,
    name: 'Carga MW',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 7,
    icon: null,
    path: '/transporte/mw/carga-mw',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 10,
    name: 'Listar MW',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 7,
    icon: null,
    path: '/transporte/mw/listar-mw',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 11,
    name: 'Anel',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: 'circle-o-notch',
    path: '/transporte/anel',
    component: 'Anel',
    admin: false,
    children: null
  },
  {
    id: 12,
    name: 'Carga Anel',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 11,
    icon: null,
    path: '/transporte/anel/carga-anel',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 13,
    name: 'Listar Anel',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 11,
    icon: null,
    path: '/transporte/anel/listar-anel',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 14,
    name: 'Carga Controle FTTS',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 11,
    icon: null,
    path: '/transporte/anel/carga-controle-ftts',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 15,
    name: 'HUB',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: 'connectdevelop',
    path: '/transporte/hub',
    component: 'Hub',
    admin: false,
    children: null
  },
  {
    id: 16,
    name: 'Carga HUB',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 15,
    icon: null,
    path: '/transporte/hub/carga-hub',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 17,
    name: 'Listar HUB',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 15,
    icon: null,
    path: '/transporte/hub/listar-hub',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 18,
    name: 'Circuitos',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: 'microchip',
    path: '/transporte/circuitos',
    component: 'Circuitos',
    admin: false,
    children: null
  },
  {
    id: 19,
    name: 'Cadastrar Circuito',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 18,
    icon: null,
    path: '/transporte/circuitos/cadastrar-circuitos',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 20,
    name: 'Carga Massiva Circuitos',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 18,
    icon: null,
    path: '/transporte/circuitos/carga-massiva-circuitos',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 21,
    name: 'Listar Circuitos',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 18,
    icon: null,
    path: '/transporte/circuitos/listar-circuitos',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 22,
    name: 'Carga Taxa de Ocupação',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 18,
    icon: null,
    path: '/transporte/circuitos/carga-taxa-ocupação',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 23,
    name: 'Topologia',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: null,
    path: '/transporte/topologia',
    component: 'Topologia',
    admin: false,
    children: null
  },
  {
    id: 24,
    name: 'Mapa',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 23,
    icon: null,
    path: '/transporte/topologia/mapa',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 25,
    name: 'Relatórios',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: 'archive',
    path: '/transporte/relatorios',
    component: 'Relatorios',
    admin: false,
    children: null
  },
  {
    id: 26,
    name: 'TX Profile',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 25,
    icon: null,
    path: '/transporte/relatorios/txt-profile',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 27,
    name: 'Município Profile',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 25,
    icon: null,
    path: '/transporte/relatorios/municipio-profile',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 28,
    name: 'IDDF',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 25,
    icon: null,
    path: '/transporte/relatorios/iddf',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 29,
    name: 'Base de Anéis',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 25,
    icon: null,
    path: '/transporte/relatorios/base-aneis',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 30,
    name: 'Base de Circuitos',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 25,
    icon: null,
    path: '/transporte/relatorios/base-circuitos',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 31,
    name: 'Base de Enlaces',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 25,
    icon: null,
    path: '/transporte/relatorios/base-enlaces',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 32,
    name: 'Plano Operativo',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: 'calendar-check-o',
    path: '/transporte/plano-operativo',
    component: 'PlanoOperativo',
    admin: false,
    children: null
  },
  {
    id: 33,
    name: 'Geração de PLO',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 32,
    icon: null,
    path: '/transporte/plano-operativo/geracao-plo',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 34,
    name: 'Carga PLO',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 32,
    icon: null,
    path: '/transporte/plano-operativo/carga-plo',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 35,
    name: 'Listar PLO',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 32,
    icon: null,
    path: '/transporte/plano-operativo/listar-plo',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 36,
    name: 'Listar PLO TN',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 32,
    icon: null,
    path: '/transporte/plano-operativo/listar-plo-tn',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 37,
    name: 'Circuitos Pendentes',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 32,
    icon: null,
    path: '/transporte/plano-operativo/circuitos-pendentes',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 38,
    name: 'AMBV',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: null,
    path: '/transporte/ambv',
    component: 'AMBV',
    admin: false,
    children: null
  },
  {
    id: 39,
    name: 'Carga BoQ',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 38,
    icon: null,
    path: '/transporte/ambv/carga-boq',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 40,
    name: 'Base de Máscaras',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 38,
    icon: null,
    path: '/transporte/ambv/base-mascaras',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 41,
    name: 'Projeto Executivo',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: null,
    path: '/transporte/projeto-executivo',
    component: 'ProjetoExecutivo',
    admin: false,
    children: null
  },
  {
    id: 42,
    name: 'Carga Projeto Executivo',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 41,
    icon: null,
    path: '/transporte/projeto-executivo/carga-projeto-executivo',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 43,
    name: 'Listar Projeto Executivo',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 41,
    icon: null,
    path: '/transporte/projeto-executivo/listar-projeto-executivo',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 44,
    name: 'Rota Unifilar',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: null,
    path: '/transporte/rota-unifilar',
    component: 'RotaUnifilar',
    admin: false,
    children: null
  },
  {
    id: 45,
    name: 'Base Física',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 44,
    icon: null,
    path: '/transporte/rota-unifilar/base-fisica',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 46,
    name: 'Topologia',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 44,
    icon: null,
    path: '/transporte/rota-unifilar/topologia',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 47,
    name: 'Base Gerencial',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: null,
    path: '/transporte/base-gerencial',
    component: 'BaseGerencial',
    admin: false,
    children: null
  },
  {
    id: 48,
    name: 'Carga Gerencial',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 47,
    icon: null,
    path: '/transporte/base-gerencial/carga-base-gerencial',
    component: 'Carga',
    admin: false,
    children: null
  },
  {
    id: 49,
    name: 'Listar Base Gerencial',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 47,
    icon: null,
    path: '/transporte/base-gerencial/listar-base-gerencial',
    component: 'Listar',
    admin: false,
    children: null
  },
  {
    id: 50,
    name: 'Planejamento',
    description: null,
    nivel: 'MENU',
    parent_id: 3,
    icon: null,
    path: '/transporte/planejamento',
    component: 'Planejamento',
    admin: false,
    children: null
  },
  {
    id: 51,
    name: 'Planejamento de Engenharia',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 50,
    icon: null,
    path: '/transporte/planejamento/planejamento-engenharia',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 52,
    name: 'Base de Cadeias',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 50,
    icon: null,
    path: '/transporte/planejamento/base-cadeias',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 54,
    name: 'Carga PLO Acesso',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 53,
    icon: null,
    path: '/acesso/plano-operativo/carga-plo-acesso',
    component: 'Carga',
    admin: false,
    children: null
  },
  {
    id: 55,
    name: 'Listar PLO Acesso',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 53,
    icon: null,
    path: '/acesso/plano-operativo/listar-plo-acesso',
    component: 'Listar',
    admin: false,
    children: null
  },
  {
    id: 56,
    name: 'Projeto Executivo',
    description: null,
    nivel: 'MENU',
    parent_id: 4,
    icon: null,
    path: '/acesso/plano-executivo',
    component: 'ProjetoExecutivo',
    admin: false,
    children: null
  },
  {
    id: 57,
    name: 'Carga Projeto Executivo',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 56,
    icon: null,
    path: '/acesso/plano-executivo/carga-projeto-executivo',
    component: 'Carga',
    admin: false,
    children: null
  },
  {
    id: 58,
    name: 'Listar Projeto Executivo',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 56,
    icon: null,
    path: '/acesso/plano-executivo/listar-projeto-executivo',
    component: 'Listar',
    admin: false,
    children: null
  },
  {
    id: 59,
    name: 'Relatórios',
    description: null,
    nivel: 'MENU',
    parent_id: 4,
    icon: 'archive',
    path: '/acesso/relatorios',
    component: 'Relatorios',
    admin: false,
    children: null
  },
  {
    id: 61,
    name: 'Projeto E2E',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 60,
    icon: null,
    path: '/psbi/psbi/projeto-e2e',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 62,
    name: 'Licenciamento',
    description: null,
    nivel: 'MENU',
    parent_id: 6,
    icon: null,
    path: '/anatel/licenciamento',
    component: 'LicenciamentoAnatel',
    admin: false,
    children: null
  },
  {
    id: 63,
    name: 'Listar Licenciamento',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 62,
    icon: null,
    path: '/anatel/licenciamento/listar-licenciamento',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 64,
    name: 'Criar Network Number',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 62,
    icon: null,
    path: '/anatel/licenciamento/criar-network-number',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 65,
    name: 'Carga Licenciamento',
    description: null,
    nivel: 'SUBMENU',
    parent_id: 62,
    icon: null,
    path: '/anatel/licenciamento/carga-licenciamento',
    component: null,
    admin: false,
    children: null
  },
  {
    id: 8,
    name: 'Administrador',
    description: 'Modulo referente as funcionalidades de administrador',
    nivel: 'MODULO',
    parent_id: null,
    icon: 'users',
    path: '/administrador',
    component: 'Administrador',
    admin: true,
    children: null
  },
  {
    id: 3,
    name: 'Transporte',
    description: 'Modulo referente as funcionalidades de transporte',
    nivel: 'MODULO',
    parent_id: null,
    icon: 'users',
    path: '/transporte',
    component: 'Transporte',
    admin: false,
    children: null
  },
  {
    id: 4,
    name: 'Acesso',
    description: 'Modulo referente as funcionalidades de acesso',
    nivel: 'MODULO',
    parent_id: null,
    icon: 'users',
    path: '/acesso',
    component: 'Acesso',
    admin: false,
    children: null
  },
  {
    id: 5,
    name: 'PSBI',
    description: 'Modulo referente as funcionalidades de psbi',
    nivel: 'MODULO',
    parent_id: null,
    icon: 'users',
    path: '/psbi',
    component: 'PSBI',
    admin: false,
    children: null
  },
  {
    id: 6,
    name: 'Anatel',
    description: 'Modulo referente as funcionalidades de anatel',
    nivel: 'MODULO',
    parent_id: null,
    icon: 'users',
    path: '/anatel',
    component: 'Anatel',
    admin: false,
    children: null
  }
];

export default data.sort((a, b) => (a.id > b.id) ? 1 : -1);;
